// LOGGER CONSTANTS
export const DATABASE_LOGGER = 'DATABASE'
export const EXPRESS_API_LOGGER = 'EXPRESS_API'
export const PUBSUB_LOGGER = 'PUBSUB'
export const CREATE_USER_USE_CASE_LOGGER = 'CREATE_USER_USE_CASE_LOGGER'
export const CREATE_DISCOUNT_USE_CASE_LOGGER = 'CREATE_DISCOUNT_USE_CASE_LOGGER'

// PUBSUB CONSTANTS
export const USER_CREATED_EVENT = 'USER_CREATED_EVENT'
export const DISCOUNT_CREATED_EVENT = 'DISCOUNT_CREATED_EVENT'
